import type { LayoutConfig } from "./layout.types";

const CHILD_CARD_WIDTH = 315;
const CHILD_CARD_HEIGHT = 243;

export const layoutDesktopLg: LayoutConfig = {
  id: "desktop-lg",
  minWidth: 1024,
  maxWidth: 1279,
  canvasWidth: 930,
  extraHeight: 200,
  scaleWithContainer: true,
  items: [
    { id: "node1", x: 436, y: 80, width: 56, height: 56 },
    { id: "node1-c1", x: 50, y: 230, width: CHILD_CARD_WIDTH, height: CHILD_CARD_HEIGHT },
    { id: "node1-c2", x: 560, y: 280, width: CHILD_CARD_WIDTH, height: CHILD_CARD_HEIGHT },
    { id: "node1-c3", x: 20, y: 580, width: CHILD_CARD_WIDTH, height: CHILD_CARD_HEIGHT },

    { id: "node2", x: 436, y: 1100, width: 56, height: 56 },
    { id: "node2-c1", x: 530, y: 1260, width: CHILD_CARD_WIDTH, height: CHILD_CARD_HEIGHT },
    { id: "node2-c2", x: 60, y: 1320, width: CHILD_CARD_WIDTH, height: CHILD_CARD_HEIGHT },

    { id: "node3", x: 436, y: 1850, width: 56, height: 56 },
    { id: "node3-c1", x: 20, y: 2030, width: CHILD_CARD_WIDTH, height: CHILD_CARD_HEIGHT },
    { id: "node3-c2", x: 555, y: 2100, width: CHILD_CARD_WIDTH, height: CHILD_CARD_HEIGHT },

    { id: "node4", x: 436, y: 2650, width: 56, height: 56 },
    { id: "node4-c1", x: 540, y: 2850, width: CHILD_CARD_WIDTH, height: CHILD_CARD_HEIGHT },
    { id: "node4-c2", x: 35, y: 2920, width: CHILD_CARD_WIDTH, height: CHILD_CARD_HEIGHT },
    { id: "node4-c3", x: 510, y: 3260, width: CHILD_CARD_WIDTH, height: CHILD_CARD_HEIGHT },

    { id: "node5", x: 436, y: 3800, width: 56, height: 56 },
    { id: "node5-c1", x: 30, y: 3980, width: CHILD_CARD_WIDTH, height: CHILD_CARD_HEIGHT },
    { id: "node5-c2", x: 570, y: 4100, width: CHILD_CARD_WIDTH, height: CHILD_CARD_HEIGHT },

    { id: "node6", x: 436, y: 4550, width: 56, height: 56 },
    { id: "node6-p1", x: 130, y: 4720, width: CHILD_CARD_WIDTH, height: CHILD_CARD_HEIGHT },
    { id: "node6-p2", x: 560, y: 4780, width: CHILD_CARD_WIDTH, height: CHILD_CARD_HEIGHT },
    { id: "node6-p3", x: 70, y: 5050, width: CHILD_CARD_WIDTH, height: CHILD_CARD_HEIGHT },
    { id: "node6-p4", x: 600, y: 5090, width: CHILD_CARD_WIDTH, height: CHILD_CARD_HEIGHT },
    { id: "node6-p5", x: 130, y: 5390, width: CHILD_CARD_WIDTH, height: CHILD_CARD_HEIGHT },
    { id: "node6-p6", x: 490, y: 5430, width: CHILD_CARD_WIDTH, height: CHILD_CARD_HEIGHT },
  ],
  edges: [
    {
      from: "node1",
      to: "node1-c1",
      fromAnchor: "bottom",
      toAnchor: "right",
      via: [{ x: 464, y: 346 }],
    },
    {
      from: "node1",
      to: "node1-c2",
      fromAnchor: "bottom",
      toAnchor: "left",
      via: [{ x: 468, y: 396 }],
    },
    {
      from: "node1",
      to: "node1-c3",
      fromAnchor: "bottom",
      toAnchor: "right",
      via: [{ x: 462, y: 550 }],
    },
    {
      from: "node1",
      to: "node2",
      fromAnchor: "bottom",
      toAnchor: "top",
      via: [{ x: 464, y: 700 }],
    },
    {
      from: "node2",
      to: "node2-c1",
      fromAnchor: "bottom",
      toAnchor: "left",
      via: [{ x: 458, y: 1360 }],
    },
    {
      from: "node2",
      to: "node2-c2",
      fromAnchor: "bottom",
      toAnchor: "right",
      via: [{ x: 467, y: 1400 }],
    },
    {
      from: "node2",
      to: "node3",
      fromAnchor: "bottom",
      toAnchor: "top",
      via: [{ x: 464, y: 1400 }],
    },
    {
      from: "node3",
      to: "node3-c1",
      fromAnchor: "bottom",
      toAnchor: "right",
      via: [{ x: 466, y: 2120 }],
    },
    {
      from: "node3",
      to: "node3-c2",
      fromAnchor: "bottom",
      toAnchor: "left",
      via: [{ x: 460, y: 2170 }],
    },
    {
      from: "node3",
      to: "node4",
      fromAnchor: "bottom",
      toAnchor: "top",
      via: [{ x: 464, y: 2400 }],
    },
    {
      from: "node4",
      to: "node4-c1",
      fromAnchor: "bottom",
      toAnchor: "left",
      via: [{ x: 460, y: 2930 }],
    },
    {
      from: "node4",
      to: "node4-c2",
      fromAnchor: "bottom",
      toAnchor: "right",
      via: [{ x: 467, y: 2970 }],
    },
    {
      from: "node4",
      to: "node4-c3",
      fromAnchor: "bottom",
      toAnchor: "left",
      via: [{ x: 457, y: 3250 }],
    },
    {
      from: "node4",
      to: "node5",
      fromAnchor: "bottom",
      toAnchor: "top",
      via: [{ x: 464, y: 3400 }],
    },
    {
      from: "node5",
      to: "node5-c1",
      fromAnchor: "bottom",
      toAnchor: "right",
      via: [{ x: 457, y: 4050 }],
    },
    {
      from: "node5",
      to: "node5-c2",
      fromAnchor: "bottom",
      toAnchor: "left",
      via: [{ x: 464, y: 4130 }],
    },
    {
      from: "node5",
      to: "node6",
      fromAnchor: "bottom",
      toAnchor: "top",
      via: [{ x: 470, y: 4300 }],
    },
    {
      from: "node6",
      to: "node6-p1",
      fromAnchor: "bottom",
      toAnchor: "right",
      via: [{ x: 470, y: 4780 }],
    },
    {
      from: "node6",
      to: "node6-p2",
      fromAnchor: "bottom",
      toAnchor: "left",
      via: [{ x: 465, y: 4780 }],
    },
    {
      from: "node6",
      to: "node6-p3",
      fromAnchor: "bottom",
      toAnchor: "right",
      via: [{ x: 455, y: 5050 }],
    },
    {
      from: "node6",
      to: "node6-p4",
      fromAnchor: "bottom",
      toAnchor: "left",
      via: [{ x: 475, y: 5050 }],
    },
    {
      from: "node6",
      to: "node6-p5",
      fromAnchor: "bottom",
      toAnchor: "top",
      via: [{ x: 495, y: 5150 }],
    },
    {
      from: "node6",
      to: "node6-p6",
      fromAnchor: "bottom",
      toAnchor: "top",
      via: [{ x: 470, y: 5320 }],
    },
  ],
};
